CREATE DATABASE EVALUATION;

USE EVALUATION;

CREATE TABLE ADDRESS(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	COUNTY VARCHAR(50),
	STATE VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	NUMBER INTEGER,
	PRIMARY KEY (ID)
);
